### ISSUE TITLE
sir i am getting this problem 

### ISSUE THREAD

**Issue by AryamanGurjar** [SRDeveloperVishal/hacktoberfest2021#22]
It is showing that the project is not participating
![img 2](https://user-images.githubusercontent.com/82881082/135723791-a21df5d1-e986-400e-9750-5d4ea6631c41.PNG)

**Comment by SRDeveloperVishal** [comment]
now its working correct please try again

**Comment by AryamanGurjar** [comment]
Thank You Sir
😄
Now it is showing 14 days to mature 😊

**Comment by sadathshariff** [comment]
Hi, @SRDeveloperVishal Please look into the #85 PR and review it ,Have made some changes and added the details
